### ISSUE TITLE
Should I scale the outputs for SumQE models from 0-1 by 5?

### ISSUE THREAD

**Issue by saiprabhakar** [danieldeutsch/sacrerouge#127]
Hi,
I am trying to evaluate my Summ model on your SumQE metrics.

The SumQE paper has tables with values for Q1-5 in the 1-5 range, but the output from the models (with the example in the Readme file in the SumQE repo) is most of the time 0-1 range (once it was 1.03).

Am I missing something or is it just scaling?

Thanks

**Comment by danieldeutsch** [comment]
I believe what is happening is that the final output layer from the original code has no activation function to force the output to be between 0 and 1 (see [here](https://github.com/danieldeutsch/SumQE/blob/98ffbf57adc072a32a3478f6acc91bf0664433a8/src/BERT_experiments/Bert_model.py#L73-L87)), so sometimes the value could be outside of this range. I am not an author of that work, but I would suggest clipping values > 1 to be 1 and < 0 to be 0.

**Comment by saiprabhakar** [comment]
Yep, that makes sense. 
Also, to close the loop on my question, I noticed in the [training data prep](https://github.com/danieldeutsch/SumQE/blob/98ffbf57adc072a32a3478f6acc91bf0664433a8/src/make_datasets/make_dataset.py#L95-L104) code the human ratings are being divided by 5. So to get back the Likert scale outputs [0-5] we have to multiply the outputs by 5 (after fixing the range of the output to [0, 1] as you said).
